// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Debate struct {
	ID          int32
	MatchID     string
	DebateType  string
	Headline    string
	Description sql.NullString
	AiGenerated sql.NullBool
	DeletedAt   sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type DebateAnalytic struct {
	ID              int32
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type DebateCard struct {
	ID          int32
	DebateID    sql.NullInt32
	Stance      string
	Title       string
	Description sql.NullString
	AiGenerated sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type League struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	OwnerID     int32
	Country     sql.NullString
	Level       sql.NullInt32
	LogoUrl     sql.NullString
	Website     sql.NullString
	Founded     sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Medium struct {
	ID        int32
	MatchID   string
	MediaUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlayerProfile struct {
	ID         uuid.UUID
	UserID     int32
	TeamID     uuid.NullUUID
	Position   string
	Age        int32
	Country    string
	HeightCm   int32
	Pace       int32
	Shooting   int32
	Passing    int32
	Stamina    int32
	Dribbling  int32
	Defending  int32
	Physical   int32
	IsVerified bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Team struct {
	ID          uuid.UUID
	Name        string
	LeagueID    uuid.NullUUID
	State       sql.NullString
	Country     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	ManagerID   uuid.NullUUID
	LogoUrl     sql.NullString
	City        sql.NullString
	Founded     sql.NullInt32
	Stadium     sql.NullString
	Capacity    sql.NullInt32
}

type TeamManager struct {
	ID         uuid.UUID
	UserID     int32
	LeagueID   uuid.UUID
	TeamID     uuid.NullUUID
	Title      sql.NullString
	Experience sql.NullInt32
	Bio        sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
	IsAdmin   bool
}

type Verification struct {
	ID              uuid.UUID
	PlayerProfileID uuid.UUID
	VerifierUserID  int32
	CreatedAt       time.Time
}

type Vote struct {
	ID           int32
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
	CreatedAt    sql.NullTime
}
