// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Medium struct {
	ID        int32
	MatchID   string
	MediaUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	ID        int32
	Name      string
	Country   string
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
