// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID              int32
	DebateID        sql.NullInt32
	ParentCommentID sql.NullInt32
	UserID          sql.NullInt32
	Content         string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type Debate struct {
	ID          int32
	MatchID     string
	DebateType  string
	Headline    string
	Description sql.NullString
	AiGenerated sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type DebateAnalytic struct {
	ID              int32
	DebateID        sql.NullInt32
	TotalVotes      sql.NullInt32
	TotalComments   sql.NullInt32
	EngagementScore sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type DebateCard struct {
	ID          int32
	DebateID    sql.NullInt32
	Stance      string
	Title       string
	Description sql.NullString
	AiGenerated sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Medium struct {
	ID        int32
	MatchID   string
	MediaUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	ID        int32
	Name      string
	Country   string
	State     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Firstname string
	Lastname  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Vote struct {
	ID           int32
	DebateCardID sql.NullInt32
	UserID       sql.NullInt32
	VoteType     string
	Emoji        sql.NullString
	CreatedAt    sql.NullTime
}
