// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: teams.sql

package database

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, country, state)
VALUES ($1, $2, $3)
RETURNING id, name, country, state, created_at, updated_at
`

type CreateTeamParams struct {
	Name    string
	Country string
	State   string
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Name, arg.Country, arg.State)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
