[build]
builder = "nixpacks"
buildCommand = "go build -o main ."
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "./main"
healthcheckPath = "/v1/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
DB_URL = "${DB_URL}"
REDIS_URL = "redis://${REDISUSER}:${REDISPASSWORD}@${REDISHOST}:${REDISPORT}"
FOOTBALL_API_KEY = "${FOOTBALL_API_KEY}" 