[build]
builder = "nixpacks"
buildCommand = "go build -o main ."

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
PORT = "8080" 